### PR TITLE
Added Random Planet,  created a dropdown selection for all API choices

### PR DESCRIPTION
**Pull request by graph1994**
Added a selection for all API choices, you can select a random planet and it will display its info

### CODE REVIEW

**Comment by graph1994** [comment]
Looks like I need a way to modulate the repeated code so that I can pass this, I'll finish this tomorrow!

**Comment by alexkramer** [comment]
I would not worry about that code quality violation at the moment. The ideal solution would be to write a general SWAPI service which can call any of the endpoints (instead of one per endpoint). I purposefully did not write the person service to be general originally because I wanted there to be a bit more to the tasks other than simply creating views.

**Comment by graph1994** [comment]
Alright So should I refactor this to make a general purpose SWAPI service, that can handle all of api calls? Am I on the right track with the drop down selection or do you want something different to change between them?  I just need allite more info on all of the 'Add Support for ...' issues

**Comment by alexkramer** [comment]
You do not need to go ahead and create a general service (someone can take that up separately). I think the dropdown is a fine way of toggling between them for now!

**Pull request merged**
